server:
    port: ${MY_SERVER_PORT}

springdoc:
  swagger-ui:
    layout: BaseLayout
  
security:
    jwt:
        secret-key: ${MY_JWT_SECRET_KEY}
        expiration: ${MY_JWT_EXPIRATION}
        refresh-token:
            expiration: ${MY_JWT_REFRESH_TOKEN_EXPIRATION}
mail:
  baseUrl: ${MY_MAIL_BASEURL}

spring:
  application:
    name: ${MY_APPLICATION_NAME}
  jackson:
    time-zone: ${MY_TIME_ZONE}
  datasource:
    url: ${MY_DATASOURCE_URL}
    username: ${MY_DATASOURCE_USERNAME}
    password: ${MY_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${MY_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${MY_JPA_SHOW_SQL}
    open-in-view: ${MY_JPA_OPEN_IN_VIEW}
  mail:
    host: ${MY_MAIL_HOST}
    port: ${MY_MAIL_PORT}
    username: ${MY_MAIL_USERNAME}
    password: ${MY_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MY_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MY_MAIL_SMTP_STARTTLS_ENABLE}
