server:
    port: ${MY_SERVER_PORT}

security:
    jwt:
        secret-key: ${MY_JWT_SECRET_KEY}
        expiration: ${MY_JWT_EXPIRATION}
        refresh-token:
            expiration: ${MY_JWT_REFRESH_TOKEN_EXPIRATION}

spring:
  application:
    name: ${MY_APPLICATION_NAME}
  datasource:
    url: ${MY_DATASOURCE_URL}
    username: ${MY_DATASOURCE_USERNAME}
    password: ${MY_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${MY_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${MY_JPA_SHOW_SQL}
    open-in-view: ${MY_JPA_OPEN_IN_VIEW}
